### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by eleweek** [andrerpena/chatjs#6]
Hi!

I'm considering about using your plugin, it looks really nice, however it isn't free software, and I can't use it legally.

How about licensing under some good permissible free software/open source license, like BSD?

**Comment by raxan** [comment]
any news about this?

**Comment by kressly** [comment]
Still no news ? Can we have the license to use free or is this project dead and the creator no longer available ? This is a nice project anyway

**Comment by andrerpena** [comment]
I just included the license file.. I didn't have much time to work on this project in the last few months.. I plan to go back and move it forward.. but I can't guarantee anything.

**Comment by eleweek** [comment]
Thank you for your work!

And thank you for licensing it under a very permissible license. I'm closing this issue, since the code is licensed under MIT license now(IANAL). 

>  I plan to go back and move it forward.. but I can't guarantee anything.

It would be great to see more code from you. :)
